### ISSUE TITLE
Can't run application without Redux Dev Tools 

### ISSUE THREAD

**Issue by geekyrajshri** [code-for-cause/tech-conferences#16]
**Bug**
 the application via [link](http://tech-conferences.surge.sh/)  does not load site until we install redux dev tools.

**Desktop:**
 - Browser [chrome, safari, firefox]

**Screenshots**
Adding screenshots too.

<img width="1440" alt="screenshot 2018-11-27 at 11 07 54 pm" src="https://user-images.githubusercontent.com/8193580/49100376-cb540780-f299-11e8-98b6-7b5d4f3c6f8d.png">
<img width="1440" alt="screenshot 2018-11-27 at 11 08 47 pm" src="https://user-images.githubusercontent.com/8193580/49100390-d27b1580-f299-11e8-8bbe-39f1108ad620.png">

**Comment by vikaskyadav** [comment]
@TheGooner93 Is it because of the redux dev tools extension in compose in `store.js`? Let me know so that we can fix it.

**Comment by TheGooner93** [comment]
@vikaskyadav  let me have a look, will get back  to you ..

**Comment by vikaskyadav** [comment]
yeah. You can do it in the same PR of yours but the wordcloud issue will take time right? Let me know when can we finish the word cloud.

**Comment by TheGooner93** [comment]
Alright will do.

**Comment by TheGooner93** [comment]
hi @geekyrajshri @vikaskyadav I have provided a fix as part of the PR https://github.com/code-for-cause/tech-conferences/pull/13 , please have a look.

**Comment by vikaskyadav** [comment]
Thanks @TheGooner93 . I'll have a look at it.

**Comment by TheGooner93** [comment]
@vikaskyadav @geekyrajshri I think you can close this issue.
